name: Generate Daily Article

on:
  schedule:
    # Run daily at 9:00 AM UTC (10:00 AM CET)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create Firebase Service Account file
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > mobilegames-win-firebase-adminsdk-fbsvc-e75d0dfbc9.json

    - name: Generate and publish article
      run: node scripts/generate-article-template.js
      env:
        NODE_ENV: production

    - name: Build site with new article
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: mobilegames-win
        channelId: live

    - name: Clean up service account file
      if: always()
      run: rm -f mobilegames-win-firebase-adminsdk-fbsvc-e75d0dfbc9.json